file was successfully transfered to server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,31 @@
-  1 #!/usr/bin/env bash
-  2 # The path to the file to be transferred.
-  3 # The IP of the server to transfer the file to.
-  4 # The username that scp connects with.
-  5 # The path to the SSH private key that scp uses.
-  6
-  7 if [ $# -lt 4 ]
-  8 then
-  9   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
- 10 else
- 11   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
- 12 fi
+#!/usr/bin/env bash
+# Checking for command line arguments
+
+if [ $# -lt 4 ]
+
+then
+
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+
+  exit 1
+
+fi
+
+# Assigning parameters to variables
+path_to_files=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# Disabling strict host key checking
+ scr -o "StrictHostKeyCkecking" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+ # Checking if the transfer was successful
+
+ if [$? -eq o]
+ then
+         echo "FILE WAS TRANSFERED SUCCESSFULL"
+ else
+         echo "FILE TRANSFER FAILED"
+
+fi
