file successfully transfered

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,30 +2,27 @@
 # Checking for command line arguments
 
 if [ $# -lt 4 ]
-
 then
-
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-
-  exit 1
-
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
 
 # Assigning parameters to variables
+
 path_to_files=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
 # Disabling strict host key checking
- scr -o "StrictHostKeyCkecking" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+scr -o "StrictHostKeyCkecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
 
  # Checking if the transfer was successful
-
- if [$? -eq o]
+ if [ $? -eq 0 ]
  then
-         echo "FILE WAS TRANSFERED SUCCESSFULL"
+	 echo "FILE WAS TRANSFERED SUCCESSFULL"
  else
-         echo "FILE TRANSFER FAILED"
-
-fi
+	 echo "FILE TRANSFER FAILED"
+ fi
